dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.3
compiler:
  solc:
    version: "0.8.9"
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.3"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
